# Generated by Django 5.2 on 2025-07-05 13:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='loginattempt',
            table='auth_login_attempt',
        ),
        migrations.AlterModelTable(
            name='passwordhistory',
            table='auth_password_history',
        ),
        migrations.AlterModelTable(
            name='token',
            table='auth_token',
        ),
        migrations.AlterModelTable(
            name='user',
            table='auth_user',
        ),
        migrations.AlterModelTable(
            name='userpermissionoverride',
            table='auth_permission_override',
        ),
        migrations.AlterModelTable(
            name='usersession',
            table='auth_user_session',
        ),
    ]
