# Generated by Django 5.2 on 2025-08-09 08:46

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0002_alter_loginattempt_table_alter_passwordhistory_table_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='PasswordEntry',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(help_text='Name or title for this password', max_length=255)),
                ('site', models.URLField(blank=True, help_text='Website URL', max_length=500)),
                ('username', models.CharField(blank=True, help_text='Username/email for this account', max_length=255)),
                ('encrypted_password', models.TextField()),
                ('encryption_salt', models.BinaryField(max_length=32)),
                ('notes', models.TextField(blank=True)),
                ('expires_at', models.DateTimeField(blank=True, help_text='When this password expires', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('last_accessed', models.DateTimeField(blank=True, null=True)),
                ('is_favorite', models.BooleanField(default=False)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='password_entries', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'password_entries',
                'ordering': ['-is_favorite', '-updated_at'],
            },
        ),
        migrations.CreateModel(
            name='PasswordEntryHistory',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('encrypted_password', models.TextField()),
                ('encryption_salt', models.BinaryField(max_length=32)),
                ('changed_at', models.DateTimeField(auto_now_add=True)),
                ('change_reason', models.CharField(blank=True, max_length=255)),
                ('changed_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('password_entry', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='password_history', to='authentication.passwordentry')),
            ],
            options={
                'db_table': 'password_entry_history',
                'ordering': ['-changed_at'],
            },
        ),
        migrations.CreateModel(
            name='PasswordFolder',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('icon', models.CharField(blank=True, max_length=50)),
                ('color', models.CharField(blank=True, help_text='Hex color code', max_length=7)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='subfolders', to='authentication.passwordfolder')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='password_folders', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'password_folders',
                'ordering': ['name'],
                'unique_together': {('user', 'name', 'parent')},
            },
        ),
        migrations.AddField(
            model_name='passwordentry',
            name='folder',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='entries', to='authentication.passwordfolder'),
        ),
        migrations.CreateModel(
            name='PasswordTag',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50)),
                ('color', models.CharField(blank=True, help_text='Hex color code', max_length=7)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='password_tags', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'password_tags',
                'ordering': ['name'],
                'unique_together': {('user', 'name')},
            },
        ),
        migrations.AddField(
            model_name='passwordentry',
            name='tags',
            field=models.ManyToManyField(blank=True, related_name='entries', to='authentication.passwordtag'),
        ),
        migrations.CreateModel(
            name='PasswordAccessLog',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('action', models.CharField(choices=[('view', 'Viewed'), ('copy', 'Copied'), ('update', 'Updated'), ('share', 'Shared'), ('delete', 'Deleted')], max_length=50)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('user_agent', models.TextField(blank=True)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('password_entry', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='access_logs', to='authentication.passwordentry')),
            ],
            options={
                'db_table': 'password_access_logs',
                'ordering': ['-timestamp'],
                'indexes': [models.Index(fields=['password_entry', 'timestamp'], name='password_ac_passwor_800e55_idx'), models.Index(fields=['user', 'timestamp'], name='password_ac_user_id_3bd4c4_idx')],
            },
        ),
        migrations.CreateModel(
            name='PasswordShareLink',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('share_token', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('max_views', models.IntegerField(default=1, help_text='Maximum number of times this can be viewed')),
                ('current_views', models.IntegerField(default=0)),
                ('expires_at', models.DateTimeField()),
                ('require_authentication', models.BooleanField(default=False)),
                ('allowed_email', models.EmailField(blank=True, help_text='Restrict access to specific email', max_length=254)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('last_accessed', models.DateTimeField(blank=True, null=True)),
                ('accessed_by_ip', models.GenericIPAddressField(blank=True, null=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='created_shares', to=settings.AUTH_USER_MODEL)),
                ('password_entry', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='share_links', to='authentication.passwordentry')),
            ],
            options={
                'db_table': 'password_share_links',
                'indexes': [models.Index(fields=['share_token'], name='password_sh_share_t_8e3e02_idx'), models.Index(fields=['expires_at'], name='password_sh_expires_0375fb_idx')],
            },
        ),
        migrations.AddIndex(
            model_name='passwordentry',
            index=models.Index(fields=['user', 'name'], name='password_en_user_id_6e2c78_idx'),
        ),
        migrations.AddIndex(
            model_name='passwordentry',
            index=models.Index(fields=['user', 'site'], name='password_en_user_id_89cc00_idx'),
        ),
        migrations.AddIndex(
            model_name='passwordentry',
            index=models.Index(fields=['expires_at'], name='password_en_expires_660591_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='passwordentry',
            unique_together={('user', 'name', 'site')},
        ),
    ]
