# Generated by Django 5.2 on 2025-09-27 07:06

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("authentication", "0004_passwordexpirationnotification"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="loginattempt",
            options={"ordering": ["-timestamp"]},
        ),
        migrations.AlterModelOptions(
            name="passwordexpirationnotification",
            options={"ordering": ["-sent_at"]},
        ),
        migrations.AlterModelOptions(
            name="passwordhistory",
            options={"ordering": ["-created_at"]},
        ),
        migrations.AlterModelOptions(
            name="passwordsharelink",
            options={"ordering": ["-created_at"]},
        ),
        migrations.AlterModelOptions(
            name="userpermissionoverride",
            options={"ordering": ["-created_at"]},
        ),
        migrations.AlterModelOptions(
            name="usersession",
            options={"ordering": ["-last_activity"]},
        ),
        migrations.AlterField(
            model_name="passwordentry",
            name="expires_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="passwordentry",
            name="name",
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name="passwordentry",
            name="site",
            field=models.URLField(blank=True, max_length=500),
        ),
        migrations.AlterField(
            model_name="passwordentry",
            name="username",
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name="passwordfolder",
            name="color",
            field=models.CharField(blank=True, max_length=7),
        ),
        migrations.AlterField(
            model_name="passwordsharelink",
            name="allowed_email",
            field=models.EmailField(blank=True, max_length=254),
        ),
        migrations.AlterField(
            model_name="passwordsharelink",
            name="max_views",
            field=models.IntegerField(default=1),
        ),
        migrations.AlterField(
            model_name="passwordtag",
            name="color",
            field=models.CharField(blank=True, max_length=7),
        ),
        migrations.AddIndex(
            model_name="loginattempt",
            index=models.Index(
                fields=["email", "timestamp"], name="auth_login__email_afc65b_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="loginattempt",
            index=models.Index(
                fields=["ip_address", "timestamp"],
                name="auth_login__ip_addr_fe958d_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="passwordaccesslog",
            index=models.Index(
                fields=["action", "timestamp"], name="password_ac_action_78e48e_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="passwordentry",
            index=models.Index(
                fields=["user", "is_favorite"], name="password_en_user_id_98fdca_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="passwordentryhistory",
            index=models.Index(
                fields=["password_entry", "changed_at"],
                name="password_en_passwor_cb92be_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="passwordsharelink",
            index=models.Index(
                fields=["created_by"], name="password_sh_created_4b3c7e_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="usersession",
            index=models.Index(
                fields=["user", "is_active"], name="auth_user_s_user_id_be2038_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="usersession",
            index=models.Index(
                fields=["last_activity"], name="auth_user_s_last_ac_b4f4ce_idx"
            ),
        ),
    ]
