# Generated by Django 5.2 on 2025-10-18 16:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0005_alter_loginattempt_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='passwordsharelink',
            name='encrypted_password_share',
            field=models.TextField(default=''),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='passwordsharelink',
            name='share_encryption_salt',
            field=models.BinaryField(default=b'', max_length=32),
            preserve_default=False,
        ),
    ]
